-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE IF NOT EXISTS properties
(
  id                                     BIGSERIAL     PRIMARY KEY,
  msg_uuid                               TEXT          NOT NULL,
  msg_timestamp                          TIMESTAMP     NOT NULL,
  case_reference	                       TEXT          NOT NULL,
  advice	                               TEXT,
  allocate_to_responder_target	         TEXT,
  assigned_team                          TEXT,
  assigned_unit                          TEXT,
  assigned_user                          TEXT,
  auto_created_case	                     TEXT,
  case_ref	                             TEXT,
  case_response_deadline	               TEXT,
  case_task                              TEXT,
  case_type                              TEXT,
  case_status                            TEXT,
  channel	                               TEXT,
  comment_count	                         TEXT,
  correspondent_address_line1            TEXT,
  correspondent_address_line2            TEXT,
  correspondent_address_line3            TEXT,
  correspondent_country                  TEXT,
  correspondent_email                    TEXT,
  correspondent_forename                 TEXT,
  correspondent_postcode                 TEXT,
  correspondent_surname                  TEXT,
  correspondent_telephone                TEXT,
  correspondent_title                    TEXT,
  correspondence_type	                   TEXT,
  created	                               TEXT,
  creator	                               TEXT,
  date_of_letter	                       TEXT,
  date_received	                         TEXT,
  draft_response_target	                 TEXT,
  hmpo_response	                         TEXT,
  home_secretary_reply	                 TEXT,
  is_grouped_master	                     TEXT,
  is_grouped_slave	                     TEXT,
  is_linked_case	                       TEXT,
  markup_decision	                       TEXT,
  markup_minister	                       TEXT,
  markup_topic	                         TEXT,
  markup_team                            TEXT,
  markup_unit	                           TEXT,
  member	                               TEXT,
  minutes_collated	                     TEXT,
  modified	                             TEXT,
  modifier	                             TEXT,
  mp_ref	                               TEXT,
  name	                                 TEXT,
  nodedbid	                             TEXT,
  nodeuuid	                             TEXT,
  ogd_name                               TEXT,
  original_drafter_team   	             TEXT,
  original_drafter_unit	                 TEXT,
  original_drafter_user	                 TEXT,
  owner_updated_datetime	               TEXT,
  parly_dispatch	                       TEXT,
  pq_api_created_case	                   TEXT,
  priority	                             TEXT,
  reply_to_address_line1                 TEXT,
  reply_to_address_line2                 TEXT,
  reply_to_address_line3                 TEXT,
  reply_to_country                       TEXT,
  reply_to_email                         TEXT,
  reply_to_name                          TEXT,
  reply_to_postcode                      TEXT,
  reply_to_telephone                     TEXT,
  reply_to_number_ten_copy	             TEXT,
  responder_hub_target	                 TEXT,
  return_case_at	                       TEXT,
  returned_count	                       TEXT,
  reviewed_by_perm_sec	                 TEXT,
  reviewed_by_spads	                     TEXT,
  round_robin	                           TEXT,
  secondary_correspondent_reply_to	     TEXT,
  secondary_topic                        TEXT,
  signed_by_home_sec	                   TEXT,
  signed_by_lords_minister	             TEXT,
  status_updated_datetime	               TEXT,
  task_updated_datetime	                 TEXT,
  third_party_correspondent_address_line1 TEXT,
  third_party_correspondent_address_line2 TEXT,
  third_party_correspondent_address_line3 TEXT,
  third_party_correspondent_country      TEXT,
  third_party_correspondent_email        TEXT,
  third_party_correspondent_forename     TEXT,
  third_party_correspondent_organisation TEXT,
  third_party_correspondent_postcode     TEXT,
  third_party_correspondent_reply_to      TEXT,
  third_party_correspondent_surname      TEXT,
  third_party_correspondent_telephone    TEXT,
  third_party_correspondent_title        TEXT,
  urn_suffix	                           TEXT,

  CONSTRAINT properties_id_idempotent UNIQUE (msg_uuid,msg_timestamp)
);